version: '3.2'
services:
  db:
    image: postgres:13.2
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: 
      - .env
    # ports:
    #   - "5432:5432"
    network_mode: host

  web:
    build:
      context: .
      target: dev
      args:
        - APP_NAME
        - USER
        - MIX_ENV
        - SECRET_KEY_BASE
        - LIVE_VIEW_SIGNING_SALT
        - SPARKPOST_API_KEY
        - FQDN
        - STATIC_URL
        - LOGFLARE_API_KEY
        - LOGFLARE_DRAIN_ID
        - POSTGRES_PASSWORD
        - DATABASE_URL
        - TEST_DATABASE_URL
        - OBAN_WEB_LICENSE_KEY
    volumes:
      - type: bind
        source: .
        target: /app
      # - type: bind
      #   source: /home/${USER}
      #   target: /home/${USER}
    # ports:
    #   - "4000:4000"
    network_mode: host
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ${APP_NAME}_dev
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: localhost
      MIX_ENV: dev
      PORT: 4000
    env_file: 
      - .env
    depends_on:
      - db
    working_dir: /app
    command:
      - ./run.docker-compose.sh
# Define the volumes
volumes:
  pgdata: